import { createReducer } from "../../utils/redux";
export const USER_REQUEST_LOGIN_API = "USER_REQUEST_LOGIN_API";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAILED = "USER_LOGIN_FAILED";
export const USER_LOGOUT_CLEAR = "USER_LOGOUT_CLEAR";

export const USER_SIGN_UP_REQUEST = "USER_SIGN_UP_REQUEST";
export const USER_SIGN_UP_SUCCESS = "USER_SIGN_UP_SUCCESS";
export const USER_SIGN_UP_FAILED = "USER_SIGN_UP_FAILED";
export const USER_SIGN_UP_CLEAR = "USER_SIGN_UP_CLEAR";

export const USER_UPDATE_INFO_REQUEST = "USER_UPDATE_INFO_REQUEST";
export const USER_UPDATE_INFO_SUCCESS = "USER_UPDATE_INFO_SUCCESS";
export const USER_UPDATE_INFO_FAILED = "USER_UPDATE_INFO_FAILED";

export const GET_ALL_USER_REQUEST = "GET_ALL_USER_REQUEST";
export const GET_ALL_USER_SUCCESS = "GET_ALL_USER_SUCCESS";
export const GET_ALL_USER_FAILED = "GET_ALL_USER_FAILED";

export const USER_ENROLL_REQUEST = "USER_ENROLL_REQUEST";
export const USER_ENROLL_SUCCESS = "USER_ENROLL_SUCCESS";
export const USER_ENROLL_FAILED = "USER_ENROLL_FAILED";
export const USER_ENROLL_CLEAR = "USER_ENROLL_CLEAR";

export const MASK_DONE_COURSE_QUERY = "MASK_DONE_COURSE_QUERY";
export const MASK_DONE_COURSE_SUCCESS = "MASK_DONE_COURSE_SUCCESS";
export const MASK_DONE_COURSE_FAILED = "MASK_DONE_COURSE_FAILED";
export const MASK_DONE_COURSE_CLEAR = "MASK_DONE_COURSE_CLEAR";

export const ADD_STUDENT_ENROLL_REQUEST = "ADD_STUDENT_ENROLL_REQUEST";
export const ADD_STUDENT_ENROLL_SUCCESS = "ADD_STUDENT_ENROLL_SUCCESS";
export const ADD_STUDENT_ENROLL_FAILED = "ADD_STUDENT_ENROLL_FAILED";
export const ADD_STUDENT_ENROLL_CLEAR = "ADD_STUDENT_ENROLL_CLEAR";

export const ADD_COMMENT_COURSE_REQUEST = "ADD_COMMENT_COURSE_REQUEST";
export const ADD_COMMENT_COURSE_SUCCESS = "ADD_COMMENT_COURSE_SUCCESS";
export const ADD_COMMENT_COURSE_FAILED = "ADD_COMMENT_COURSE_FAILED";
export const ADD_COMMENT_COURSE_CLEAR = "ADD_COMMENT_COURSE_CLEAR";

export const USERS_DASH_BOARD = "USERS_DASH_BOARD";
export const USERS_DASH_BOARD_SUCCESS = "USERS_DASH_BOARD_SUCCESS";
export const USERS_DASH_BOARD_FAILED = "USERS_DASH_BOARD_FAILED";

export const USER_FETCH_INFO_REQUEST = "USER_FETCH_INFO_REQUEST";
// example APIs Redux-Saga
const UserReducer = createReducer(
  USER_REQUEST_LOGIN_API,
  USER_LOGIN_SUCCESS,
  USER_LOGIN_FAILED,
  USER_LOGOUT_CLEAR
);

const UserFetchInfoReducer = createReducer(
  USER_FETCH_INFO_REQUEST,
  USER_LOGIN_SUCCESS,
  USER_LOGIN_FAILED,
  USER_LOGOUT_CLEAR
);

const UserSignUpReducer = createReducer(
  USER_SIGN_UP_REQUEST,
  USER_SIGN_UP_SUCCESS,
  USER_SIGN_UP_FAILED,
  USER_SIGN_UP_CLEAR
);

const UserUpdateInfoReducer = createReducer(
  USER_UPDATE_INFO_REQUEST,
  USER_UPDATE_INFO_SUCCESS,
  USER_UPDATE_INFO_FAILED
);
const GetAllUserReducer = createReducer(
  GET_ALL_USER_REQUEST,
  GET_ALL_USER_SUCCESS,
  GET_ALL_USER_FAILED
);

const UserEnrollReducer = createReducer(
  USER_ENROLL_REQUEST,
  USER_ENROLL_SUCCESS,
  USER_ENROLL_FAILED,
  USER_ENROLL_CLEAR
);
const MaskDoneCourse = createReducer(
  MASK_DONE_COURSE_QUERY,
  MASK_DONE_COURSE_SUCCESS,
  MASK_DONE_COURSE_FAILED,
  MASK_DONE_COURSE_CLEAR
);

const AddStudentEnrollReducer = createReducer(
  ADD_STUDENT_ENROLL_REQUEST,
  ADD_STUDENT_ENROLL_SUCCESS,
  ADD_STUDENT_ENROLL_FAILED,
  ADD_STUDENT_ENROLL_CLEAR
);
const AddCommentCourseReducer = createReducer(
  ADD_COMMENT_COURSE_REQUEST,
  ADD_COMMENT_COURSE_SUCCESS,
  ADD_COMMENT_COURSE_FAILED,
  ADD_COMMENT_COURSE_CLEAR
);
const UsersDashBoardReducer = createReducer(
  USERS_DASH_BOARD,
  USERS_DASH_BOARD_SUCCESS,
  USERS_DASH_BOARD_FAILED,
);

export {
  UserReducer,
  UserSignUpReducer,
  UserUpdateInfoReducer,
  UserFetchInfoReducer,
  GetAllUserReducer,
  UserEnrollReducer,
  MaskDoneCourse,
  AddStudentEnrollReducer,
  AddCommentCourseReducer,
  UsersDashBoardReducer
};
