export { default as Excel } from "./Excel.png";
export { default as Lock } from "./Lock.png";
export { default as UnLock } from "./UnLock.png";
export { default as Slide } from "./Slide.png";
export { default as AvatarUser } from "./AvatarUser.jpg";
export { default as IconPlay } from "./IconPlay.png";
export { default as Users } from "./Users.png";
export { default as WatingIcon } from "./watingicon.png";
export { default as Word } from "./Word.png";
export { default as PP } from "./PP.png";
export {};
